config/routes.rb
Falcon::Application.routes.draw do
  devise_for :account, :controllers => { :registrations => "account/registrations", :omniauth_callbacks => "account/omniauth_callbacks" }
  resources :blogposts do
    resources :comments
  end

  resources :showcases do
    resources :comments
  end

  resources :relationships
  resources :favorites

  resources :accounts do
    member do
      get :following, :followers
    end
  end

  namespace :account do
    resource :profile, :only => [:show, :edit, :update]
    resource :language_settings, :only => [:edit, :update]

    resources :pictures do
      resources :comments
      resources :likes, :only => [:create]

      collection do
        post :upload
        post :apply_filter
      end
    end

    scope ":profile_id", :as => :view do
      resources :pictures, :only => [:index, :show]

      get "" => "profiles#show"
    end
  end

  devise_for :affiliate, :controllers => { :registrations => "affiliate/registrations" }

  namespace :affiliate do
    resource :business_profiles, :only => [:edit, :update]
    resource :language_settings, :only => [:edit, :update]
  end

  devise_for :admin

  namespace :admin do
    resource :profile, :only => [:edit, :update]

    resources :accounts
    resources :admins
    resources :affiliates

    root :to => "accounts#index"
  end

  get "home/index"
  get "home/showcase_by_filter"
  get "home/picture_by_filter"
  
  resources :galleries
  root :to => "home#index" 
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :favoritable, :polymorphic => true
  belongs_to :account
  attr_accessible :account_id
end
# == Schema Information
#
# Table name: favorites
#
#  id               :integer(4)      not null, primary key
#  favoritable_id   :integer(4)
#  favoritable_type :string(255)
#  account_id       :integer(4)
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#

app/controllers/favorites_controller.rb
# -*- coding: utf-8 -*-
class FavoritesController < ApplicationController
  before_filter :authenticate_account!

  def index
    @favorites = current_account.favorites
  end


  def create
    @favorite = Favorite.create
    item = Picture.find_by_id(params[:favorite_picture_id]) if params[:favorite_picture_id]
    item = Showcase.find_by_id(params[:favorite_showcase_id]) if params[:favorite_showcase_id]
    account = Account.find_by_id(params[:favorite_account_id])

    if(item)
      @favorite.update_attribute(:favoritable, item)
      @favorite.account = account
      if @favorite.save
        flash[:success] = "Marked as favorite!"
      end
    end
    redirect_to account_profile_path
  end

  def destroy
    favorite = Favorite.find_by_id(params[:id])
    favorite.delete
    redirect_to account_profile_path
  end


end

# Started POST "/favorites" for 127.0.0.1 at 2012-11-06 15:02:02 +0530
#Processing by FavoritesController#create as HTML
#  Parameters: {"utf8"=>"✓", "authenticity_token"=>"qbvVYVIBU6HqIzRHG/K5OEQUaAE8FlhZ3PGLrSjARmU=", "favorite_account_id"=>"1", "favorite_picture_id"=>"3", "commit"=>"Favorite"}

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/views/favorites/index.html.erb
<h2> Manage Favorites(<%= @favorites.count %>) </h2>
<div class = "well" >
  <h3>Showcases:</h3>
  <ol>
    <% @favorites.each do |favorite| %>
      <% if  favorite.favoritable_type.to_s  == "Showcase" %>
        <% showcase = Showcase.find_by_id(favorite.favoritable_id)
           %>
        <li>
          <p><h4>Name: <%= showcase.name %></h4></p>
          <% picture = showcase.cover_picture %>
          <% if picture %>
            <% if picture.image.present? %>
              <%= image_tag picture.image.url(:preview) %>
            <% end %>
          <% else %>
            <i> This showcase has no cover picture! </i>
          <% end %>
          <p> <%= showcase.favorites.count %> users(s) marked this showcase as a
            Favorite.</p>
          <%= render 'shared/unfavorite',:favorite=>
                current_account.get_favorite(showcase) %>
        </li>
      <% end %>
    <% end %>
  </ol>
</div>

<div class = "well" >
  <h3>Pictures:</h3>
  <ol>
    <% @favorites.each do |favorite| %>
      <% if  favorite.favoritable_type.to_s  == "Picture" %>
        <% picture = Picture.find_by_id(favorite.favoritable_id) %>
        <li>
          <div class="title">
            <h3><%= link_to picture.title, picture_url(picture) %></h3>
          </div>
          <div class="image">
            <%= link_to image_tag(picture.image.url(:preview)), picture_url(picture) %>
          </div>
          <div class="author">
            by <%= link_to picture.attachable.account.username, account_view_url(:profile_id => picture.attachable.unique_id) %>
          </div>
          <p><%= picture.favorites.count %> user(s) marked this picture
            as their favorite</p>
          <%= render 'shared/unfavorite',:favorite=> current_account.get_favorite(picture) %>
        </li>
      <% end %>
    <% end %>
  </ol>
</div>