config/routes.rb
Falcon::Application.routes.draw do
  devise_for :account, :controllers => { :registrations => "account/registrations", :omniauth_callbacks => "account/omniauth_callbacks" }
  resources :blogposts do
    resources :comments
  end

  resources :showcases do
    resources :comments
  end

  resources :relationships
  resources :favorites

  resources :accounts do
    member do
      get :following, :followers
    end
  end

  namespace :account do
    resource :profile, :only => [:show, :edit, :update]
    resource :language_settings, :only => [:edit, :update]

    resources :pictures do
      resources :comments
      resources :likes, :only => [:create]

      collection do
        post :upload
        post :apply_filter
      end
    end

    scope ":profile_id", :as => :view do
      resources :pictures, :only => [:index, :show]

      get "" => "profiles#show"
    end
  end

  devise_for :affiliate, :controllers => { :registrations => "affiliate/registrations" }

  namespace :affiliate do
    resource :business_profiles, :only => [:edit, :update]
    resource :language_settings, :only => [:edit, :update]
  end

  devise_for :admin

  namespace :admin do
    resource :profile, :only => [:edit, :update]

    resources :accounts
    resources :admins
    resources :affiliates

    root :to => "accounts#index"
  end

  get "home/index"
  get "home/showcase_by_filter"
  get "home/picture_by_filter"
  
  resources :galleries
  root :to => "home#index" 
end

app/views/shared/_favorite.html.erb
<%= form_tag('/favorites') do -%>
  <div>
    <%= hidden_field_tag 'favorite_account_id', current_account.id %>
    <%= hidden_field_tag "favorite_#{item.class.to_s.downcase}_id", item.id %>
  </div>
  <%= submit_tag "Favorite", :class => "btn btn-large btn-primary" %>
<% end -%>

app/views/shared/_showcase_favorites.html.erb
<div class="well">
  <h4>Favorites</h4>
  <%= showcase.favorites.count %> users(s) marked this showcase as a
  Favorite.
  <% if current_account %>
    <% if current_account.favorited?(showcase) %>
      <%= render 'shared/unfavorite',:favorite=> current_account.get_favorite(showcase) %>
    <% else %>
      <%= render 'shared/favorite', :item => showcase %>
    <% end %>
  <% end %>
</div>

app/views/shared/_unfavorite.html.erb
<%= form_for(favorite, html: { method: :delete }) do |f| %>
  <%= f.submit "Unfavorite", class: "btn btn-large btn-danger" %>
<% end %>