config/routes.rb
Falcon::Application.routes.draw do
  devise_for :account, :controllers => { :registrations => "account/registrations", :omniauth_callbacks => "account/omniauth_callbacks" }
  resources :blogposts do
    resources :comments
  end

  resources :showcases do
    resources :comments
  end

  resources :relationships
  resources :favorites

  resources :accounts do
    member do
      get :following, :followers
    end
  end

  namespace :account do
    resource :profile, :only => [:show, :edit, :update]
    resource :language_settings, :only => [:edit, :update]

    resources :pictures do
      resources :comments
      resources :likes, :only => [:create]

      collection do
        post :upload
        post :apply_filter
      end
    end

    scope ":profile_id", :as => :view do
      resources :pictures, :only => [:index, :show]

      get "" => "profiles#show"
    end
  end

  devise_for :affiliate, :controllers => { :registrations => "affiliate/registrations" }

  namespace :affiliate do
    resource :business_profiles, :only => [:edit, :update]
    resource :language_settings, :only => [:edit, :update]
  end

  devise_for :admin

  namespace :admin do
    resource :profile, :only => [:edit, :update]

    resources :accounts
    resources :admins
    resources :affiliates

    root :to => "accounts#index"
  end

  get "home/index"
  get "home/showcase_by_filter"
  get "home/picture_by_filter"
  
  resources :galleries
  root :to => "home#index" 
end

app/views/admin/admins/_filters.html.erb
<div class="accordion">
  <div class="accordion-group">
    <div class="accordion-heading">
      <%= link_to t('admin.filters.title'), '#filter', :class => 'accordion-toggle', 'data-toggle' => 'collapse' %>
    </div>
    <div class="accordion-body collapse <%= params[:q].present? ? 'in' : '' %>" id="filter">
      <%= search_form_for @query, :url => collection_url, :builder => SimpleForm::FormBuilder, :wrapper => :light, :html => { :class => 'search-form' } do |f| %>
        <%= hidden_field_tag(:sort_name, params[:sort_name]) if params[:sort_name] %>
        <%= hidden_field_tag(:sort_dir, params[:sort_dir]) if params[:sort_dir] %>
        <%= hidden_field_tag(:per_page, params[:per_page]) if params[:per_page] %>
        <%= f.input :email_cont, :as => :string, :placeholder => t('admin.filters.email_contains') %>
        <%= f.input :admin_profile_username_cont, :placeholder => t('admin.filters.username_contains') %>
        <%= f.input :admin_profile_first_name_cont, :placeholder => t('admin.filters.first_name_contains') %>
        <%= f.input :admin_profile_last_name_cont, :placeholder => t('admin.filters.last_name_contains') %>
        <div class="form-actions">
          <%= f.submit t('helpers.actions.search'), :class => 'btn btn-primary' %>
          <%= link_to t('helpers.actions.clear'), collection_url, :class => 'btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/admins/_form.html.erb
<%= simple_form_for [:admin, resource], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :email, :input_html => { :class => 'input-xxlarge' } %>
  <%= f.input :password, :input_html => { :class => 'input-xxlarge' } %>
  <%= f.input :password_confirmation, :input_html => { :class => 'input-xxlarge' } %>
  <%= f.input :admin_level, :collection => Admin::UI_ADMIN_LEVELS, :input_html => { :class => 'input-xxlarge' }, :prompt => t('helpers.please_select') %>
  <%= f.simple_fields_for :admin_profile do |profile| %>
    <%= profile.input :username, :input_html => { :class => 'input-xxlarge' } %>
    <%= profile.input :first_name, :input_html => { :class => 'input-xxlarge' } %>
    <%= profile.input :last_name, :input_html => { :class => 'input-xxlarge' } %>
  <% end %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), collection_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/admins/_grid.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= sortable_header(Admin.human_attribute_name(:id), :id) %></th>
    <th><%= sortable_header(Admin.human_attribute_name(:email), :email) %></th>
    <th><%= sortable_header(Admin.human_attribute_name(:admin_level), :admin_level) %></th>
    <th><%= sortable_header(AdminProfile.human_attribute_name(:username), :admin_profile_username) %></th>
    <th><%= sortable_header(AdminProfile.human_attribute_name(:first_name), :admin_profile_first_name) %></th>
    <th><%= sortable_header(AdminProfile.human_attribute_name(:last_name), :admin_profile_last_name) %></th>
    <th><%= sortable_header(Admin.human_attribute_name(:last_sign_in_at), :last_sign_in_at) %></th>
    <th><%= sortable_header(Admin.human_attribute_name(:created_at), :created_at) %></th>
    <th><%= sortable_header(Admin.human_attribute_name(:updated_at), :updated_at) %></th>
    <th><%=t '.actions', :default => t('helpers.actions.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% collection.each do |item| %>
    <tr>
      <td><%= link_to item.id, resource_path(item) %></td>
      <td><%= item.email %></td>
      <td><%= item.admin_level %></td>
      <td><%= item.admin_profile.username rescue '' %></td>
      <td><%= item.admin_profile.first_name rescue '' %></td>
      <td><%= item.admin_profile.last_name rescue '' %></td>
      <td><%= item.last_sign_in_at ? l(item.last_sign_in_at) : t('helpers.never') %></td>
      <td><%=l item.created_at %></td>
      <td><%=l item.updated_at %></td>
      <td>
        <% if current_admin.is_super_admin? %>
          <%= link_to t('.edit', :default => t('helpers.actions.edit')), edit_resource_path(item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t('helpers.actions.destroy')), resource_path(item), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger' %>
         <% end %>

         <% if current_admin.is_site_admin? && !item.is_super_admin? %>
         <%= link_to t('.edit', :default => t('helpers.actions.edit')), edit_resource_path(item), :class => 'btn btn-mini' %>
         <%= link_to t('.destroy', :default => t('helpers.actions.destroy')), resource_path(item), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger' %>
         <% end %>
         <%= link_to t('.view', :default => t('helpers.actions.view')), resource_path(item), :class => 'btn btn-mini' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<% if current_admin.is_view_only? || current_admin.is_user_admin? %>
       <h3> Sorry you are a <%= current_admin.admin_level %>, you can list user settings but not modify them </h3>
<% else %>
  <%= render :partial => 'form' %>
<% end %>

app/views/admin/admins/show.html.erb
<p>
  <strong><%= Admin.human_attribute_name(:email) %>:</strong><br>
  <%= resource.email %>
</p>
<p>
  <strong><%= Admin.human_attribute_name(:admin_level) %>:</strong><br>
  <%= resource.admin_level %>
</p>
<p>
  <strong><%= AdminProfile.human_attribute_name(:username) %>:</strong><br>
  <%= resource.admin_profile.username rescue '' %>
</p>
<p>
  <strong><%= AdminProfile.human_attribute_name(:first_name) %>:</strong><br>
  <%= resource.admin_profile.first_name rescue '' %>
</p>
<p>
  <strong><%= AdminProfile.human_attribute_name(:last_name) %>:</strong><br>
  <%= resource.admin_profile.last_name rescue '' %>
</p>
<p>
<p>
  <strong><%= Admin.human_attribute_name(:last_sign_in_at) %>:</strong><br>
  <%= resource.last_sign_in_at ? l(resource.last_sign_in_at) : t('helpers.never') %>
</p>
<p>
  <strong><%= Admin.human_attribute_name(:created_at) %>:</strong><br>
  <%= resource.created_at %>
</p>
<p>
  <strong><%= Admin.human_attribute_name(:updated_at) %>:</strong><br>
  <%= resource.updated_at %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")), collection_path, :class => 'btn'  %>
  <% if current_admin.is_super_admin? %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_resource_path, :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), resource_path, :method => 'delete', :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger' %>
  <% end %>
</div>